constants = (
  ("C_RGB", "-> RGB"), 
  ("C_HSV", "-> HSV"), 
  ("C_HUE", "-> Hue"), 
  ("C_VALUE", "-> Val"), 
    (None, None),
  ("C_TIME", "t"), 
  ("C_TIMESHIFT", "t<<"), 
  ("C_INDEX", "i"), 
  ("C_RANDOM8", "rnd"), 
  ("C_RANDC", "rnd*"), 
    (None, None),
  ("C_RSHIFT", ">>"), 
  ("C_LSHIFT", "<<"), 
  ("C_BITAND", "&"), 
  ("C_BITOR", "|"), 
  ("C_BITXOR", "^"), 
  ("C_BITNOT", "~"), 
  ("C_AND", "&&"), 
  ("C_OR", "||"), 
  ("C_NOT", "!"), 
    (None, None),
  ("C_PLUS", "+"), 
  ("C_MINUS", "-"), 
  ("C_TIMES", "*"), 
  ("C_DIVIDE", "/"), 
  ("C_MOD", "%"), 
  ("C_INC", "++"), 
  ("C_DEC", "--"), 
  ("C_DIFF", "diff"), 
    (None, None),
  ("C_EQ", "=="), 
  ("C_NE", "!="), 
  ("C_GT", ">"), 
  ("C_GE", ">="), 
  ("C_LT", "<"), 
  ("C_LE", "<="), 
    (None, None),
  ("C_IFTE", "if"), 
    (None, None),
  ("C_ABS", "abs"), 
  ("C_MIN", "min"), 
  ("C_MAX", "max"), 
    (None, None),
  ("C_REGA", "a"), 
  ("C_REGB", "b"), 
  ("C_REGC", "c"), 
  ("C_REGD", "d"), 
  ("C_REGZ", "z"), 
  ("C_REGN", "reg"), 
  ("C_REGCYC", "rc"), 
    (None, None),
  ("C_STA", "-> a"), 
  ("C_STB", "-> b"), 
  ("C_STC", "-> c"), 
  ("C_STD", "-> d"), 
  ("C_STZ", "-> z"), 
  ("C_STN", "-> reg"), 
  ("C_STCYC", "-> rc"), 
    (None, None),
  ("C_STAIF", "-> a if"), 
  ("C_STBIF", "-> b if"), 
  ("C_STCIF", "-> c if"), 
  ("C_STDIF", "-> d if"), 
  ("C_STZIF", "-> z if"), 
  ("C_STNIF", "-> reg if"), 
  ("C_STCYCIF", "-> rc if"), 
    (None, None),
  ("C_LOOPSTART", "do"), 
  ("C_LOOPREG", "l"), 
  ("C_LOOPMAX", "loop max"), 
    (None, None),
  ("C_TDIFF", "|t-|"), 
  ("C_IDIFF", "|i-|"), 
    (None, None),
  ("C_PRINT", "print"), 
)

other = (
  ("REG_WIDTH" , "2"),
  ("REG_IDX"   , "(1<<REG_WIDTH)"),
  ("REG_MAX"   , "(REG_IDX - 1)"),
  ("STACK_SIZE", "64"),
)
